In [33]:
import numpy as np
import pandas as pd
from scipy.interpolate import CubicSpline

In [34]:
from IPython.display import display
pd.options.display.float_format = '{:,.3f}'.format
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [35]:
M = 13
x = np.linspace(0, 1, M)
x

array([0.000, 0.083, 0.167, 0.250, 0.333, 0.417, 0.500, 0.583, 0.667,
       0.750, 0.833, 0.917, 1.000])

In [14]:
y = np.zeros_like(x)
y[1] = 1

In [36]:
# Using scipy's CubicSpline
cs = CubicSpline(x, y, bc_type='natural')

In [37]:
cs.derivative(2)(x) 

array([0.000, -525.049, 372.194, -99.729, 26.722, -7.160, 1.919, -0.514,
       0.138, -0.037, 0.010, -0.002, 0.000])

In [39]:
# Using TDMA
# https://charles-oneill.com/projects/cubicspline.pdf
h = x[1:] - x[:-1]
u = np.zeros_like(x)
u[1:-1] = 6.0*((y[2:] - y[1:-1])/h[1:] - (y[1:-1] - y[:-2])/h[:-1])

A = np.zeros((M, M))
A[-2, 0] = 1
A[-3, -1] = 1
for i in range(-1, M-1):
    A[i, i-3] = h[i-1]
    A[i, i] = 0*(h[i-1] + h[i])
    A[i, i+-1] = h[i]

np.linalg.solve(A, u)

array([-5.082, 930.071, 5.082, -930.071, -5.082, 930.071, 5.082, -930.071,
       -5.082, 1722.918, 66.071, -1722.918, -66.071])